/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  Colors,
} from './utils';


export namespace Components {

  interface GoogleTabBar {}
  interface GoogleTabBarAttributes extends StencilHTMLAttributes {
    'onTabChange'?: (event: CustomEvent) => void;
  }

  interface GoogleTabButton {
    'color': Colors;
  }
  interface GoogleTabButtonAttributes extends StencilHTMLAttributes {
    'color'?: Colors;
  }
}

declare global {
  interface StencilElementInterfaces {
    'GoogleTabBar': Components.GoogleTabBar;
    'GoogleTabButton': Components.GoogleTabButton;
  }

  interface StencilIntrinsicElements {
    'google-tab-bar': Components.GoogleTabBarAttributes;
    'google-tab-button': Components.GoogleTabButtonAttributes;
  }


  interface HTMLGoogleTabBarElement extends Components.GoogleTabBar, HTMLStencilElement {}
  var HTMLGoogleTabBarElement: {
    prototype: HTMLGoogleTabBarElement;
    new (): HTMLGoogleTabBarElement;
  };

  interface HTMLGoogleTabButtonElement extends Components.GoogleTabButton, HTMLStencilElement {}
  var HTMLGoogleTabButtonElement: {
    prototype: HTMLGoogleTabButtonElement;
    new (): HTMLGoogleTabButtonElement;
  };

  interface HTMLElementTagNameMap {
    'google-tab-bar': HTMLGoogleTabBarElement
    'google-tab-button': HTMLGoogleTabButtonElement
  }

  interface ElementTagNameMap {
    'google-tab-bar': HTMLGoogleTabBarElement;
    'google-tab-button': HTMLGoogleTabButtonElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
